//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIRMA()
        {
            this.MG = new HashSet<MG>();
            this.PARTIE_ATESTY = new HashSet<PARTIE_ATESTY>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string nazwa_pelna { get; set; }
        public string nip { get; set; }
        public string regon { get; set; }
        public string ulica { get; set; }
        public string numer_dom { get; set; }
        public string numer_lokal { get; set; }
        public string kod_pocztowy { get; set; }
        public string miejscowosc { get; set; }
        public string kraj { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string www { get; set; }
        public string email { get; set; }
        public Nullable<byte> domyslna_lab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG> MG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY> PARTIE_ATESTY { get; set; }
    }
}
