//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FZLEntities1 : DbContext
    {
        public FZLEntities1()
            : base("name=FZLEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DSPEC> DSPEC { get; set; }
        public virtual DbSet<DSPECP> DSPECP { get; set; }
        public virtual DbSet<FIRMA> FIRMA { get; set; }
        public virtual DbSet<GS1_CONFIG> GS1_CONFIG { get; set; }
        public virtual DbSet<GS1_KODY> GS1_KODY { get; set; }
        public virtual DbSet<HMMG> HMMG { get; set; }
        public virtual DbSet<HMMZ> HMMZ { get; set; }
        public virtual DbSet<KH> KH { get; set; }
        public virtual DbSet<KONTRAKT> KONTRAKT { get; set; }
        public virtual DbSet<KONTRAKT_PARAM> KONTRAKT_PARAM { get; set; }
        public virtual DbSet<KONTRAKT_UMOWY> KONTRAKT_UMOWY { get; set; }
        public virtual DbSet<KONTRAKT_UMOWY_WART_PARAM> KONTRAKT_UMOWY_WART_PARAM { get; set; }
        public virtual DbSet<MAGAZYNY> MAGAZYNY { get; set; }
        public virtual DbSet<MG> MG { get; set; }
        public virtual DbSet<MG_HM> MG_HM { get; set; }
        public virtual DbSet<MG_PARAMETRY> MG_PARAMETRY { get; set; }
        public virtual DbSet<MG_PARAMETRY_WART> MG_PARAMETRY_WART { get; set; }
        public virtual DbSet<MG_POWIAZANIA> MG_POWIAZANIA { get; set; }
        public virtual DbSet<MG_POZYCJE> MG_POZYCJE { get; set; }
        public virtual DbSet<MG_RODZAJE> MG_RODZAJE { get; set; }
        public virtual DbSet<MG_STANY> MG_STANY { get; set; }
        public virtual DbSet<MG_WG> MG_WG { get; set; }
        public virtual DbSet<MG_WG_POWIAZANIA> MG_WG_POWIAZANIA { get; set; }
        public virtual DbSet<MG_WG_POZYCJE> MG_WG_POZYCJE { get; set; }
        public virtual DbSet<MG_WG_POZYCJE_OPAKOWANIA> MG_WG_POZYCJE_OPAKOWANIA { get; set; }
        public virtual DbSet<MG_WG_STANY> MG_WG_STANY { get; set; }
        public virtual DbSet<MZ_HM> MZ_HM { get; set; }
        public virtual DbSet<OPAKOWANIA> OPAKOWANIA { get; set; }
        public virtual DbSet<OPAKOWANIA_FK> OPAKOWANIA_FK { get; set; }
        public virtual DbSet<OPAKOWANIA_RODZAJE> OPAKOWANIA_RODZAJE { get; set; }
        public virtual DbSet<OWSBZ> OWSBZ { get; set; }
        public virtual DbSet<OWSBZ_SCHEM> OWSBZ_SCHEM { get; set; }
        public virtual DbSet<PARTIE> PARTIE { get; set; }
        public virtual DbSet<PARTIE_2> PARTIE_2 { get; set; }
        public virtual DbSet<PARTIE_ATESTY> PARTIE_ATESTY { get; set; }
        public virtual DbSet<PARTIE_ATESTY_PARAM> PARTIE_ATESTY_PARAM { get; set; }
        public virtual DbSet<PARTIE_ATESTY_WART> PARTIE_ATESTY_WART { get; set; }
        public virtual DbSet<PARTIE_DOSTAWCY> PARTIE_DOSTAWCY { get; set; }
        public virtual DbSet<PARTIE_FK> PARTIE_FK { get; set; }
        public virtual DbSet<PLACE> PLACE { get; set; }
        public virtual DbSet<PLACE_PRACOWNICY> PLACE_PRACOWNICY { get; set; }
        public virtual DbSet<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual DbSet<PROD> PROD { get; set; }
        public virtual DbSet<PROD_HMDW> PROD_HMDW { get; set; }
        public virtual DbSet<PROD_HMTW> PROD_HMTW { get; set; }
        public virtual DbSet<PROD_LINIE> PROD_LINIE { get; set; }
        public virtual DbSet<PROD_LINIE_MASZYNY> PROD_LINIE_MASZYNY { get; set; }
        public virtual DbSet<PROD_LINIE_PARAM> PROD_LINIE_PARAM { get; set; }
        public virtual DbSet<PROD_LINIE_PARAM_WART> PROD_LINIE_PARAM_WART { get; set; }
        public virtual DbSet<PROD_LINIE_PW> PROD_LINIE_PW { get; set; }
        public virtual DbSet<PROD_MAGAZYN> PROD_MAGAZYN { get; set; }
        public virtual DbSet<PROD_MAGAZYNY> PROD_MAGAZYNY { get; set; }
        public virtual DbSet<PROD_MASZYNY> PROD_MASZYNY { get; set; }
        public virtual DbSet<PROD_MASZYNY_KOSZTY> PROD_MASZYNY_KOSZTY { get; set; }
        public virtual DbSet<PROD_MASZYNY_MONIT> PROD_MASZYNY_MONIT { get; set; }
        public virtual DbSet<PROD_MASZYNY_PARAM> PROD_MASZYNY_PARAM { get; set; }
        public virtual DbSet<PROD_MASZYNY_PARAM_DEF> PROD_MASZYNY_PARAM_DEF { get; set; }
        public virtual DbSet<PROD_MASZYNY_PARAM_WART> PROD_MASZYNY_PARAM_WART { get; set; }
        public virtual DbSet<PROD_MASZYNY_PW> PROD_MASZYNY_PW { get; set; }
        public virtual DbSet<PROD_MASZYNY_ZL> PROD_MASZYNY_ZL { get; set; }
        public virtual DbSet<PROD_MG> PROD_MG { get; set; }
        public virtual DbSet<PROD_MGDW> PROD_MGDW { get; set; }
        public virtual DbSet<PROD_MGPW> PROD_MGPW { get; set; }
        public virtual DbSet<PROD_MZ> PROD_MZ { get; set; }
        public virtual DbSet<PROD_PRODMGPW> PROD_PRODMGPW { get; set; }
        public virtual DbSet<PROD_PW> PROD_PW { get; set; }
        public virtual DbSet<PROD_TYPDK> PROD_TYPDK { get; set; }
        public virtual DbSet<PROD_ZL> PROD_ZL { get; set; }
        public virtual DbSet<PRODCONF> PRODCONF { get; set; }
        public virtual DbSet<PRODDK> PRODDK { get; set; }
        public virtual DbSet<PRODDP> PRODDP { get; set; }
        public virtual DbSet<PRODDP_FK> PRODDP_FK { get; set; }
        public virtual DbSet<PRODDP_MONIT> PRODDP_MONIT { get; set; }
        public virtual DbSet<PRODPARAM> PRODPARAM { get; set; }
        public virtual DbSet<PRODPARAM_GRUPY> PRODPARAM_GRUPY { get; set; }
        public virtual DbSet<PRODPARAM_WART> PRODPARAM_WART { get; set; }
        public virtual DbSet<SUROWCE> SUROWCE { get; set; }
        public virtual DbSet<SUROWCE_TW> SUROWCE_TW { get; set; }
        public virtual DbSet<TW> TW { get; set; }
        public virtual DbSet<UZYTKOWNICY> UZYTKOWNICY { get; set; }
        public virtual DbSet<UZYTKOWNICY_LOG> UZYTKOWNICY_LOG { get; set; }
        public virtual DbSet<UZYTKOWNICY_UPRAWNIENIA> UZYTKOWNICY_UPRAWNIENIA { get; set; }
        public virtual DbSet<WALUTY> WALUTY { get; set; }
        public virtual DbSet<PRODDP_SYM> PRODDP_SYM { get; set; }
        public virtual DbSet<PARTIE_SYM> PARTIE_SYM { get; set; }
        public virtual DbSet<PROD_MZ_SPEC> PROD_MZ_SPEC { get; set; }
        public virtual DbSet<WZ_SPECYFIKACJE> WZ_SPECYFIKACJE { get; set; }
        public virtual DbSet<WZ_SPECYFIKACJE_OPAKOWANIA> WZ_SPECYFIKACJE_OPAKOWANIA { get; set; }
        public virtual DbSet<WZ_SPECYFIKACJE_TOWARY> WZ_SPECYFIKACJE_TOWARY { get; set; }
    }
}
