//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS1_CONFIG
    {
        public int id { get; set; }
        public string kod_firmy { get; set; }
        public string nr_jednostki { get; set; }
        public string nr_jednostki_globalny { get; set; }
        public Nullable<byte> cyfra__rozszerzajaca { get; set; }
    }
}
