//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GS1_KODY
    {
        public int id { get; set; }
        public int id_prod_dp_monit { get; set; }
        public string kod_tw { get; set; }
        public string nazwa_tw { get; set; }
        public string nr_partii { get; set; }
        public string nr_getin { get; set; }
        public string kod_firmy { get; set; }
        public string nazwa_opakowania { get; set; }
        public Nullable<double> ilosc_opakowania { get; set; }
        public Nullable<double> waga_netto { get; set; }
        public Nullable<int> seria_nr { get; set; }
        public Nullable<double> waga_opakowania { get; set; }
        public string sscc { get; set; }
        public string sscc_pelny { get; set; }
        public string cyfra_kontrolna { get; set; }
        public Nullable<System.DateTime> termin { get; set; }
        public Nullable<double> waga_brutto { get; set; }
        public string termin_kod { get; set; }
    
        public virtual PRODDP_MONIT PRODDP_MONIT { get; set; }
    }
}
