//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMMZ
    {
        public int id { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<int> hmid { get; set; }
        public Nullable<int> id_hmmg { get; set; }
        public Nullable<short> flag { get; set; }
        public Nullable<short> subtypi { get; set; }
        public Nullable<short> typi { get; set; }
        public Nullable<int> super { get; set; }
        public Nullable<short> lp { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string opis { get; set; }
        public string opisdod { get; set; }
        public Nullable<double> ilosc { get; set; }
        public string jm { get; set; }
        public Nullable<short> grupaceni { get; set; }
        public Nullable<double> cena { get; set; }
        public Nullable<double> wartNetto { get; set; }
        public Nullable<int> idpozkoryg { get; set; }
        public Nullable<short> rejestri { get; set; }
        public Nullable<int> idlongname { get; set; }
        public Nullable<short> magazyn { get; set; }
        public Nullable<double> iloscjedn { get; set; }
        public Nullable<double> wartTowaru { get; set; }
        public string osoba { get; set; }
        public Nullable<double> iloscwp { get; set; }
        public Nullable<int> idhandl { get; set; }
        public Nullable<double> iloscdorozl { get; set; }
        public Nullable<double> przychod { get; set; }
        public Nullable<double> rozchod { get; set; }
        public Nullable<double> wartk { get; set; }
        public Nullable<short> lwartki { get; set; }
        public string schemat { get; set; }
        public string jmwp { get; set; }
        public string zapas { get; set; }
    
        public virtual HMMG HMMG { get; set; }
    }
}
