//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KH()
        {
            this.KONTRAKT_UMOWY = new HashSet<KONTRAKT_UMOWY>();
            this.MG_WG = new HashSet<MG_WG>();
            this.PARTIE_DOSTAWCY = new HashSet<PARTIE_DOSTAWCY>();
            this.SUROWCE = new HashSet<SUROWCE>();
        }
    
        public long id { get; set; }
        public Nullable<long> zew_id { get; set; }
        public string kod_firmy { get; set; }
        public string guid { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> subtyp { get; set; }
        public Nullable<int> znacznik { get; set; }
        public string info { get; set; }
        public string osoba { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public string dom { get; set; }
        public string lokal { get; set; }
        public string kodpocz { get; set; }
        public string rejon { get; set; }
        public string nip { get; set; }
        public Nullable<byte> statusUE { get; set; }
        public string regon { get; set; }
        public string pesel { get; set; }
        public Nullable<short> osfiz { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string www { get; set; }
        public string naglowek { get; set; }
        public string nazwisko { get; set; }
        public string imie { get; set; }
        public string bnazwa { get; set; }
        public string bkonto { get; set; }
        public string negoc { get; set; }
        public string grupacen { get; set; }
        public string typks { get; set; }
        public string typ_naliczania { get; set; }
        public string typ_ceny { get; set; }
        public Nullable<decimal> upust { get; set; }
        public string limit { get; set; }
        public Nullable<decimal> limitkwota { get; set; }
        public Nullable<decimal> limitwaluta { get; set; }
        public string rejestr_platnosci { get; set; }
        public string forma_platnosci { get; set; }
        public Nullable<decimal> stanpl { get; set; }
        public Nullable<decimal> stannl { get; set; }
        public string khfk { get; set; }
        public string zapas { get; set; }
        public string krajKod { get; set; }
        public string krajNazwa { get; set; }
        public Nullable<int> aktywny { get; set; }
        public string NazwaRodzaju { get; set; }
        public string poledod1 { get; set; }
        public string poledod2 { get; set; }
        public string poledod3 { get; set; }
        public string poledod4 { get; set; }
        public string poledod5 { get; set; }
        public string poledod6 { get; set; }
        public string poledod7 { get; set; }
        public string notatka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONTRAKT_UMOWY> KONTRAKT_UMOWY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG> MG_WG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_DOSTAWCY> PARTIE_DOSTAWCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUROWCE> SUROWCE { get; set; }
    }
}
