//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTRAKT_UMOWY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTRAKT_UMOWY()
        {
            this.KONTRAKT_UMOWY_WART_PARAM = new HashSet<KONTRAKT_UMOWY_WART_PARAM>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_kontrakt { get; set; }
        public System.DateTime data_zawarcia { get; set; }
        public string kod { get; set; }
        public string seria { get; set; }
        public long serianr { get; set; }
        public int okres { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string nazwa_tow { get; set; }
        public Nullable<long> idtow { get; set; }
        public Nullable<double> ilosc_kontrakt { get; set; }
        public Nullable<double> areal_kontrakt { get; set; }
        public Nullable<double> ilosc_dostarczona { get; set; }
        public Nullable<double> areal { get; set; }
        public Nullable<double> cena1 { get; set; }
        public Nullable<double> cena2 { get; set; }
        public string waluta { get; set; }
        public Nullable<long> khid { get; set; }
        public string khkod { get; set; }
        public string khnazwa { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khkodpocz { get; set; }
        public string khnip { get; set; }
        public string khkraj { get; set; }
        public byte status { get; set; }
        public string uwagi { get; set; }
        public string odmiana { get; set; }
        public Nullable<int> iddkfk { get; set; }
        public Nullable<int> idpozdkfk { get; set; }
        public string koddkfk { get; set; }
        public Nullable<System.DateTime> datadkfk { get; set; }
        public Nullable<System.DateTime> plattermin { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual KONTRAKT_UMOWY KONTRAKT_UMOWY1 { get; set; }
        public virtual KONTRAKT_UMOWY KONTRAKT_UMOWY2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONTRAKT_UMOWY_WART_PARAM> KONTRAKT_UMOWY_WART_PARAM { get; set; }
    }
}
