//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTRAKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTRAKT()
        {
            this.KONTRAKT_PARAM = new HashSet<KONTRAKT_PARAM>();
        }
    
        public long id { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> okres { get; set; }
        public Nullable<int> idtw { get; set; }
        public string skrot { get; set; }
        public System.DateTime data_utw { get; set; }
        public System.DateTime data_mod { get; set; }
        public string nazwa_towaru { get; set; }
        public string kod_towaru { get; set; }
        public Nullable<double> cena1 { get; set; }
        public Nullable<double> cena2 { get; set; }
        public string waluta { get; set; }
        public string wzor_wydruku { get; set; }
        public byte aktywna { get; set; }
        public string kod_firmy { get; set; }
        public byte handlowa { get; set; }
        public Nullable<short> platnosc_dni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONTRAKT_PARAM> KONTRAKT_PARAM { get; set; }
    }
}
