//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGAZYNY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAGAZYNY()
        {
            this.MG_WG_POZYCJE_OPAKOWANIA = new HashSet<MG_WG_POZYCJE_OPAKOWANIA>();
            this.PRODDP_MONIT = new HashSet<PRODDP_MONIT>();
            this.PROD_MZ_SPEC = new HashSet<PROD_MZ_SPEC>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public string kod { get; set; }
        public string adres { get; set; }
        public string nr { get; set; }
        public string miejscowosc { get; set; }
        public string kodpocztowy { get; set; }
        public string opis { get; set; }
        public byte aktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POZYCJE_OPAKOWANIA> MG_WG_POZYCJE_OPAKOWANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP_MONIT> PRODDP_MONIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MZ_SPEC> PROD_MZ_SPEC { get; set; }
    }
}
