//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_HM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_HM()
        {
            this.MZ_HM = new HashSet<MZ_HM>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_hm { get; set; }
        public Nullable<byte> flag { get; set; }
        public Nullable<byte> typi { get; set; }
        public Nullable<byte> znaczniki { get; set; }
        public Nullable<int> rodzaj { get; set; }
        public Nullable<int> katalog { get; set; }
        public string info { get; set; }
        public string osoba { get; set; }
        public string kod { get; set; }
        public string seria { get; set; }
        public Nullable<int> serianr { get; set; }
        public Nullable<int> okres { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> datasp { get; set; }
        public string opis { get; set; }
        public Nullable<int> khid { get; set; }
        public string khkod { get; set; }
        public string khnazwa { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khkodpocz { get; set; }
        public string khnip { get; set; }
        public Nullable<byte> ok { get; set; }
        public Nullable<byte> puste { get; set; }
        public Nullable<System.DateTime> termin { get; set; }
        public Nullable<double> netto { get; set; }
        public string odebrane { get; set; }
        public string typ_dk { get; set; }
        public Nullable<byte> grupaceni { get; set; }
        public Nullable<byte> rejestrVati { get; set; }
        public Nullable<int> iddokkoryg { get; set; }
        public Nullable<int> idkorekt { get; set; }
        public Nullable<byte> exp_fki { get; set; }
        public Nullable<byte> statusFK { get; set; }
        public Nullable<double> wartoscWz { get; set; }
        public Nullable<byte> magazyn { get; set; }
        public Nullable<int> idhandl { get; set; }
        public Nullable<byte> dzial { get; set; }
        public Nullable<double> przychod { get; set; }
        public Nullable<double> rozchod { get; set; }
        public Nullable<double> wartk { get; set; }
        public string schemat { get; set; }
        public string zapas { get; set; }
        public string kod_firmy { get; set; }
        public string kod_dksp { get; set; }
        public string kodpz { get; set; }
        public Nullable<int> serialpz { get; set; }
        public Nullable<int> okrespz { get; set; }
        public System.DateTime dodano { get; set; }
        public Nullable<System.DateTime> modyfikowano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MZ_HM> MZ_HM { get; set; }
    }
}
