//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_PARAMETRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_PARAMETRY()
        {
            this.MG_PARAMETRY_WART = new HashSet<MG_PARAMETRY_WART>();
        }
    
        public int id { get; set; }
        public byte typ { get; set; }
        public string kod { get; set; }
        public string grupa { get; set; }
        public Nullable<int> pozycja { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public string typ_wart { get; set; }
        public byte czy_uwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_PARAMETRY_WART> MG_PARAMETRY_WART { get; set; }
    }
}
