//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_POZYCJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_POZYCJE()
        {
            this.MG_POWIAZANIA = new HashSet<MG_POWIAZANIA>();
        }
    
        public int id { get; set; }
        public Nullable<int> super { get; set; }
        public Nullable<short> lp { get; set; }
        public Nullable<byte> typ { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string opis { get; set; }
        public string opisdod { get; set; }
        public Nullable<double> ilosc_fiz { get; set; }
        public Nullable<double> ilosc { get; set; }
        public string jm { get; set; }
        public Nullable<double> cena { get; set; }
        public Nullable<double> wartNetto { get; set; }
        public Nullable<short> magazyn { get; set; }
        public Nullable<double> iloscjedn { get; set; }
        public Nullable<double> wartTowaru { get; set; }
        public string osoba { get; set; }
        public Nullable<double> przychod { get; set; }
        public Nullable<double> rozchod { get; set; }
        public Nullable<double> wartk { get; set; }
        public string schemat { get; set; }
        public string nr_partii { get; set; }
        public Nullable<int> id_partii { get; set; }
        public string kod_fki { get; set; }
        public Nullable<int> iddk_fki { get; set; }
        public Nullable<int> idpoz_fki { get; set; }
        public string kod_firmy { get; set; }
    
        public virtual MG MG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_POWIAZANIA> MG_POWIAZANIA { get; set; }
        public virtual PARTIE PARTIE { get; set; }
    }
}
