//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_PARAMETRY_WART
    {
        public long id { get; set; }
        public int id_dk { get; set; }
        public int id_param { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> wart_int1 { get; set; }
        public Nullable<int> wart_int2 { get; set; }
        public Nullable<double> wart_float1 { get; set; }
        public Nullable<double> wart_float2 { get; set; }
        public string wart_txt1 { get; set; }
        public string uwagi { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual MG MG { get; set; }
        public virtual MG_PARAMETRY MG_PARAMETRY { get; set; }
    }
}
