//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_WG_POZYCJE_OPAKOWANIA
    {
        public int id { get; set; }
        public int id_rodzaj_opak { get; set; }
        public int idpoz { get; set; }
        public string nr_partii { get; set; }
        public string nazwa_opakowania { get; set; }
        public Nullable<double> ilosc_opakowania { get; set; }
        public Nullable<double> waga_opakowania { get; set; }
        public Nullable<double> ilew { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> idmg { get; set; }
        public string kodmg { get; set; }
        public string nazwamg { get; set; }
    
        public virtual MAGAZYNY MAGAZYNY { get; set; }
        public virtual MG_WG_POZYCJE MG_WG_POZYCJE { get; set; }
        public virtual MG_WG_POZYCJE_OPAKOWANIA MG_WG_POZYCJE_OPAKOWANIA1 { get; set; }
        public virtual MG_WG_POZYCJE_OPAKOWANIA MG_WG_POZYCJE_OPAKOWANIA2 { get; set; }
        public virtual OPAKOWANIA_RODZAJE OPAKOWANIA_RODZAJE { get; set; }
    }
}
