//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_WG_POZYCJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_WG_POZYCJE()
        {
            this.MG_WG_POWIAZANIA = new HashSet<MG_WG_POWIAZANIA>();
            this.MG_WG_POZYCJE_OPAKOWANIA = new HashSet<MG_WG_POZYCJE_OPAKOWANIA>();
        }
    
        public int id { get; set; }
        public int super { get; set; }
        public short lp { get; set; }
        public int idtw { get; set; }
        public string kod { get; set; }
        public string opis { get; set; }
        public Nullable<int> id_partii { get; set; }
        public string nr_partii { get; set; }
        public double ilosc { get; set; }
        public string jm { get; set; }
        public Nullable<double> przychod { get; set; }
        public Nullable<double> rozchod { get; set; }
        public Nullable<double> rezerwacja { get; set; }
        public string uwagi { get; set; }
        public Nullable<double> stan { get; set; }
        public string parametr1 { get; set; }
        public string parametr2 { get; set; }
        public string parametr3 { get; set; }
        public string parametr4 { get; set; }
        public string rezerwacja_opis { get; set; }
        public Nullable<System.DateTime> rezerwacja_termin { get; set; }
        public string rezerwacja_osoba { get; set; }
    
        public virtual MG_WG MG_WG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POWIAZANIA> MG_WG_POWIAZANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POZYCJE_OPAKOWANIA> MG_WG_POZYCJE_OPAKOWANIA { get; set; }
        public virtual PARTIE PARTIE { get; set; }
        public virtual TW TW { get; set; }
    }
}
