//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_WG_STANY
    {
        public int id { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public Nullable<double> stan { get; set; }
        public Nullable<double> rezerwacje { get; set; }
        public Nullable<double> stanHandl { get; set; }
        public Nullable<int> id_partii { get; set; }
        public string nr_partii { get; set; }
        public string opis { get; set; }
    
        public virtual PARTIE PARTIE { get; set; }
    }
}
