//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPAKOWANIA
    {
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string nazwa_ang { get; set; }
        public Nullable<double> wym_x { get; set; }
        public Nullable<double> wym_y { get; set; }
        public Nullable<double> wym_z { get; set; }
        public Nullable<double> waga { get; set; }
        public Nullable<double> pojemnosc { get; set; }
        public string jm { get; set; }
        public Nullable<int> id_rodzaj { get; set; }
        public string dostawca { get; set; }
        public string producent { get; set; }
        public string specyfikacja { get; set; }
        public Nullable<byte> specyfikacja_wl { get; set; }
        public Nullable<byte> specyfikacja_prod { get; set; }
        public Nullable<byte> specyfikacja_brak { get; set; }
        public string deklaracja { get; set; }
        public Nullable<System.DateTime> data_aktualizacji { get; set; }
        public Nullable<System.DateTime> dodano { get; set; }
        public Nullable<System.DateTime> zminiono { get; set; }
    }
}
