//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPAKOWANIA_FK
    {
        public int id { get; set; }
        public int id_rodzaj_opak { get; set; }
        public Nullable<int> id_dk { get; set; }
        public Nullable<int> idpoz_dk { get; set; }
        public Nullable<byte> lp_poz_dk { get; set; }
        public byte lp { get; set; }
        public string typdk { get; set; }
        public string nr_partii { get; set; }
        public string nazwa_opakowania { get; set; }
        public Nullable<double> ilosc_opakowania { get; set; }
        public Nullable<double> waga_opakowania { get; set; }
        public Nullable<double> ilew { get; set; }
        public string kod_firmy { get; set; }
    
        public virtual OPAKOWANIA_RODZAJE OPAKOWANIA_RODZAJE { get; set; }
    }
}
