//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPAKOWANIA_RODZAJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPAKOWANIA_RODZAJE()
        {
            this.MG_WG_POZYCJE_OPAKOWANIA = new HashSet<MG_WG_POZYCJE_OPAKOWANIA>();
            this.OPAKOWANIA_FK = new HashSet<OPAKOWANIA_FK>();
            this.PROD_HMTW = new HashSet<PROD_HMTW>();
            this.PRODDP_MONIT = new HashSet<PRODDP_MONIT>();
            this.PRODDP_MONIT1 = new HashSet<PRODDP_MONIT>();
            this.PROD_MZ_SPEC = new HashSet<PROD_MZ_SPEC>();
            this.PROD_MZ_SPEC1 = new HashSet<PROD_MZ_SPEC>();
            this.WZ_SPECYFIKACJE_OPAKOWANIA = new HashSet<WZ_SPECYFIKACJE_OPAKOWANIA>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string nazwa_ang { get; set; }
        public byte aktywny { get; set; }
        public Nullable<double> wym_x { get; set; }
        public Nullable<double> wym_y { get; set; }
        public Nullable<double> wym_z { get; set; }
        public Nullable<double> pojemnosc { get; set; }
        public Nullable<double> waga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POZYCJE_OPAKOWANIA> MG_WG_POZYCJE_OPAKOWANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPAKOWANIA_FK> OPAKOWANIA_FK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_HMTW> PROD_HMTW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP_MONIT> PRODDP_MONIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP_MONIT> PRODDP_MONIT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MZ_SPEC> PROD_MZ_SPEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MZ_SPEC> PROD_MZ_SPEC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WZ_SPECYFIKACJE_OPAKOWANIA> WZ_SPECYFIKACJE_OPAKOWANIA { get; set; }
    }
}
