//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWSBZ_SCHEM
    {
        public int id { get; set; }
        public int id_owsbz { get; set; }
        public Nullable<byte> lp { get; set; }
        public string nazwa_srodka { get; set; }
        public string data_zabiegu { get; set; }
        public Nullable<double> ilosc { get; set; }
    }
}
