//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE_ATESTY_PARAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIE_ATESTY_PARAM()
        {
            this.PARTIE_ATESTY_WART = new HashSet<PARTIE_ATESTY_WART>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string wart_typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY_WART> PARTIE_ATESTY_WART { get; set; }
    }
}
