//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE_ATESTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIE_ATESTY()
        {
            this.PARTIE_ATESTY_WART = new HashSet<PARTIE_ATESTY_WART>();
        }
    
        public int id { get; set; }
        public int id_partii { get; set; }
        public string nr_partii { get; set; }
        public Nullable<int> idtw { get; set; }
        public string nazwa_towaru { get; set; }
        public string nr { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<int> id_firma { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<System.DateTime> data_produkcji { get; set; }
        public Nullable<System.DateTime> termin_waznosci { get; set; }
        public Nullable<double> okres_waznosci { get; set; }
    
        public virtual FIRMA FIRMA { get; set; }
        public virtual PARTIE PARTIE { get; set; }
        public virtual TW TW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY_WART> PARTIE_ATESTY_WART { get; set; }
    }
}
