//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE_ATESTY_WART
    {
        public int id { get; set; }
        public int id_atest { get; set; }
        public int id_partia { get; set; }
        public int id_param { get; set; }
        public string wart_txt { get; set; }
        public Nullable<double> wart_float { get; set; }
        public string uwagi { get; set; }
    
        public virtual PARTIE PARTIE { get; set; }
        public virtual PARTIE_ATESTY PARTIE_ATESTY { get; set; }
        public virtual PARTIE_ATESTY_PARAM PARTIE_ATESTY_PARAM { get; set; }
    }
}
