//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIE()
        {
            this.MG = new HashSet<MG>();
            this.MG_POZYCJE = new HashSet<MG_POZYCJE>();
            this.MG_WG_POZYCJE = new HashSet<MG_WG_POZYCJE>();
            this.MG_WG_STANY = new HashSet<MG_WG_STANY>();
            this.PARTIE_2 = new HashSet<PARTIE_2>();
            this.PARTIE_ATESTY = new HashSet<PARTIE_ATESTY>();
            this.PARTIE_ATESTY_WART = new HashSet<PARTIE_ATESTY_WART>();
            this.PARTIE_DOSTAWCY = new HashSet<PARTIE_DOSTAWCY>();
            this.PARTIE_FK = new HashSet<PARTIE_FK>();
            this.PRODDP_FK = new HashSet<PRODDP_FK>();
            this.PRODDP = new HashSet<PRODDP>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> data_przyjecia { get; set; }
        public byte typ { get; set; }
        public string nr_partii { get; set; }
        public string nazwa_produktu { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod_frimy { get; set; }
        public string osoba { get; set; }
        public string uwagi { get; set; }
        public long serial { get; set; }
        public Nullable<byte> mikrobiologia { get; set; }
        public Nullable<System.DateTime> mikrobiologia_data { get; set; }
        public Nullable<int> odmiana { get; set; }
        public string odmiana_nazwa { get; set; }
        public Nullable<double> wilgotnosc { get; set; }
        public Nullable<double> czystosc { get; set; }
        public string prefix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG> MG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_POZYCJE> MG_POZYCJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POZYCJE> MG_WG_POZYCJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_STANY> MG_WG_STANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_2> PARTIE_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY> PARTIE_ATESTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY_WART> PARTIE_ATESTY_WART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_DOSTAWCY> PARTIE_DOSTAWCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_FK> PARTIE_FK { get; set; }
        public virtual TW TW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP_FK> PRODDP_FK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP> PRODDP { get; set; }
    }
}
