//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE_SYM
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data_przyjecia { get; set; }
        public byte typ { get; set; }
        public string nr_partii { get; set; }
        public string nazwa_produktu { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod_frimy { get; set; }
        public string osoba { get; set; }
        public string uwagi { get; set; }
        public Nullable<long> serial { get; set; }
        public Nullable<byte> mikrobiologia { get; set; }
        public Nullable<System.DateTime> mikrobiologia_data { get; set; }
        public Nullable<int> odmiana { get; set; }
        public string odmiana_nazwa { get; set; }
        public Nullable<double> wilgotnosc { get; set; }
        public Nullable<double> czystosc { get; set; }
        public string prefix { get; set; }
    }
}
