//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIE_DOSTAWCY
    {
        public long id { get; set; }
        public int id_partie { get; set; }
        public Nullable<long> khid { get; set; }
        public string khnazwa { get; set; }
        public string khkod { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khkodpocz { get; set; }
        public string khnip { get; set; }
        public string khkraj { get; set; }
        public string numer_tel { get; set; }
        public string uwagi { get; set; }
        public string nr_dok { get; set; }
        public Nullable<System.DateTime> data_dostawy { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual PARTIE PARTIE { get; set; }
    }
}
