//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE_PRACOWNICY
    {
        public int id { get; set; }
        public int id_pracownika { get; set; }
        public int id_listy { get; set; }
        public Nullable<float> kwota_brutto { get; set; }
        public Nullable<float> kwota_netto { get; set; }
        public float do_wyplaty { get; set; }
        public string numer_konta { get; set; }
        public string tytulem { get; set; }
        public string uwagi { get; set; }
    
        public virtual PLACE PLACE { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
    }
}
