//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLACE()
        {
            this.PLACE_PRACOWNICY = new HashSet<PLACE_PRACOWNICY>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public string numer { get; set; }
        public Nullable<System.DateTime> mc_bazowy { get; set; }
        public Nullable<System.DateTime> mc_podatkowy { get; set; }
        public Nullable<System.DateTime> mc_zus { get; set; }
        public Nullable<System.DateTime> dz_wyplaty { get; set; }
        public Nullable<System.DateTime> data_od { get; set; }
        public Nullable<System.DateTime> data_do { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<System.DateTime> data_utworzenia { get; set; }
        public Nullable<System.DateTime> data_modyfikacji { get; set; }
        public Nullable<float> laczna_kwota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLACE_PRACOWNICY> PLACE_PRACOWNICY { get; set; }
    }
}
