//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRACOWNICY()
        {
            this.PLACE_PRACOWNICY = new HashSet<PLACE_PRACOWNICY>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string drugie_imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<System.DateTime> data_ur { get; set; }
        public string pesel { get; set; }
        public string nip { get; set; }
        public string numer_ewidencyjny { get; set; }
        public string numer_konta { get; set; }
        public string kod_firmy { get; set; }
        public string ulica { get; set; }
        public string nr_domu { get; set; }
        public string nr_lokalu { get; set; }
        public string kod_pocztowy { get; set; }
        public string miejscowosc { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLACE_PRACOWNICY> PLACE_PRACOWNICY { get; set; }
    }
}
