//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD()
        {
            this.PROD_LINIE_PARAM_WART = new HashSet<PROD_LINIE_PARAM_WART>();
            this.PROD_LINIE_PW = new HashSet<PROD_LINIE_PW>();
            this.PROD_MASZYNY_MONIT = new HashSet<PROD_MASZYNY_MONIT>();
            this.PROD_MASZYNY_PARAM_WART = new HashSet<PROD_MASZYNY_PARAM_WART>();
            this.PROD_MASZYNY_PW = new HashSet<PROD_MASZYNY_PW>();
            this.PROD_PW = new HashSet<PROD_PW>();
            this.PROD_ZL = new HashSet<PROD_ZL>();
            this.PROD_ZL1 = new HashSet<PROD_ZL>();
            this.PRODDK = new HashSet<PRODDK>();
            this.PRODPARAM_WART = new HashSet<PRODPARAM_WART>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> datadk { get; set; }
        public Nullable<System.DateTime> dataprod { get; set; }
        public string nazwa { get; set; }
        public string osoba { get; set; }
        public Nullable<int> khid { get; set; }
        public string khkod { get; set; }
        public string khnazwa { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khkodpocz { get; set; }
        public string khnip { get; set; }
        public string osoba1 { get; set; }
        public string osoba2 { get; set; }
        public string osoba3 { get; set; }
        public string inneosoby { get; set; }
        public Nullable<System.DateTime> utworzono { get; set; }
        public Nullable<System.DateTime> modyfikacja { get; set; }
        public Nullable<float> ilosc_surowcow { get; set; }
        public Nullable<float> ilosc_odpadow { get; set; }
        public Nullable<float> ilosc_wyrobu_got { get; set; }
        public string jm { get; set; }
        public Nullable<int> id_rw { get; set; }
        public string waluta { get; set; }
        public Nullable<double> kurs { get; set; }
        public Nullable<double> wskaznik { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<byte> osobne_pw { get; set; }
        public string kod { get; set; }
        public Nullable<int> serial { get; set; }
        public Nullable<int> okres { get; set; }
        public Nullable<byte> typ { get; set; }
        public Nullable<byte> zakonczono { get; set; }
        public Nullable<byte> akceptowano { get; set; }
        public string opis { get; set; }
        public string opis_wg { get; set; }
        public Nullable<byte> exp_hm { get; set; }
        public Nullable<double> wart_rw { get; set; }
        public Nullable<double> wart_pw { get; set; }
        public Nullable<byte> status { get; set; }
        public string uwagi { get; set; }
        public byte czesciowa { get; set; }
        public Nullable<System.DateTime> termin_rozpoczecia { get; set; }
        public Nullable<System.DateTime> termin_zakonczenia { get; set; }
        public byte zerowa { get; set; }
        public string opis_surowce { get; set; }
        public string opis_produkcja { get; set; }
        public Nullable<byte> wycena_typ { get; set; }
        public Nullable<double> koszty_pozostale { get; set; }
        public Nullable<double> ilosc_surowcow_FK { get; set; }
        public Nullable<double> ilosc_wyrobu_gotowego_FK { get; set; }
        public Nullable<double> wartosc_rw_FK { get; set; }
        public Nullable<double> wartosc_pw_FK { get; set; }
        public Nullable<double> wartosc_opakowania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_PARAM_WART> PROD_LINIE_PARAM_WART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_PW> PROD_LINIE_PW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_MONIT> PROD_MASZYNY_MONIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PARAM_WART> PROD_MASZYNY_PARAM_WART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PW> PROD_MASZYNY_PW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_PW> PROD_PW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_ZL> PROD_ZL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_ZL> PROD_ZL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDK> PRODDK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODPARAM_WART> PRODPARAM_WART { get; set; }
    }
}
