//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_PARAM_DEF
    {
        public int id { get; set; }
        public int id_param { get; set; }
        public byte domyslnie { get; set; }
        public string wartosc { get; set; }
    
        public virtual PROD_MASZYNY_PARAM PROD_MASZYNY_PARAM { get; set; }
    }
}
