//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MGDW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_MGDW()
        {
            this.PROD_MGPW = new HashSet<PROD_MGPW>();
            this.PROD_PRODMGPW = new HashSet<PROD_PRODMGPW>();
            this.PRODDP = new HashSet<PRODDP>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public Nullable<int> typi { get; set; }
        public Nullable<int> idpozpz { get; set; }
        public Nullable<int> idkh { get; set; }
        public string khkod { get; set; }
        public string khnazwa { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kodtw { get; set; }
        public string nazwatw { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<double> iloscprod { get; set; }
        public Nullable<double> iloscdost { get; set; }
        public Nullable<double> stan { get; set; }
        public Nullable<double> iloscpz { get; set; }
        public string typdw { get; set; }
        public string nr_partii { get; set; }
        public string kod_firmy { get; set; }
        public string typ_produktu { get; set; }
        public Nullable<double> cena { get; set; }
        public string dkhandl { get; set; }
    
        public virtual PROD_MZ PROD_MZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MGPW> PROD_MGPW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_PRODMGPW> PROD_PRODMGPW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDP> PRODDP { get; set; }
    }
}
