//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PW
    {
        public int id { get; set; }
        public int id_prod { get; set; }
        public Nullable<int> id_proddp { get; set; }
        public Nullable<int> id_proddpfk { get; set; }
        public int id_proddw { get; set; }
        public Nullable<int> id_dwfk { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<double> wartosc { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string zapas { get; set; }
        public Nullable<int> id_mzfk { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD_HMDW PROD_HMDW { get; set; }
        public virtual PRODDP PRODDP { get; set; }
        public virtual PRODDP_FK PRODDP_FK { get; set; }
    }
}
