//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_MASZYNY()
        {
            this.PROD_LINIE_MASZYNY = new HashSet<PROD_LINIE_MASZYNY>();
            this.PROD_MASZYNY_PARAM = new HashSet<PROD_MASZYNY_PARAM>();
            this.PROD_MASZYNY_PW = new HashSet<PROD_MASZYNY_PW>();
            this.PROD_MASZYNY_ZL = new HashSet<PROD_MASZYNY_ZL>();
            this.PROD_MASZYNY_ZL1 = new HashSet<PROD_MASZYNY_ZL>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string producent { get; set; }
        public Nullable<System.DateTime> data_produkcji { get; set; }
        public Nullable<System.DateTime> data_przegladu { get; set; }
        public Nullable<System.DateTime> waznosc_przegladu { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<double> mocKW { get; set; }
        public byte aktywna { get; set; }
        public string czynnosci { get; set; }
        public Nullable<double> cena_kg { get; set; }
        public Nullable<double> cena_czas { get; set; }
        public Nullable<int> ilosc_osob { get; set; }
        public Nullable<double> koszt_osoba { get; set; }
        public Nullable<decimal> udzial_osoba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_MASZYNY> PROD_LINIE_MASZYNY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PARAM> PROD_MASZYNY_PARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PW> PROD_MASZYNY_PW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_ZL> PROD_MASZYNY_ZL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_ZL> PROD_MASZYNY_ZL1 { get; set; }
    }
}
