//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_PARAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_MASZYNY_PARAM()
        {
            this.PROD_MASZYNY_PARAM_DEF = new HashSet<PROD_MASZYNY_PARAM_DEF>();
            this.PROD_MASZYNY_PARAM_WART = new HashSet<PROD_MASZYNY_PARAM_WART>();
        }
    
        public int id { get; set; }
        public int id_maszyny { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public Nullable<byte> typ { get; set; }
        public string parametr { get; set; }
        public string parametr_type { get; set; }
        public Nullable<byte> czy_monit { get; set; }
        public byte aktywny { get; set; }
    
        public virtual PROD_MASZYNY PROD_MASZYNY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PARAM_DEF> PROD_MASZYNY_PARAM_DEF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PARAM_WART> PROD_MASZYNY_PARAM_WART { get; set; }
    }
}
