//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_DW
    {
        public int id { get; set; }
        public int id_fk { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<byte> typi { get; set; }
        public string kod { get; set; }
        public Nullable<int> iddw { get; set; }
        public Nullable<int> iddkpz { get; set; }
        public Nullable<int> idkh { get; set; }
        public string khnazwa { get; set; }
        public string khkod { get; set; }
        public Nullable<int> iddkzk { get; set; }
        public Nullable<int> numer { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kodtw { get; set; }
        public string opistw { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<double> iloscdosp { get; set; }
        public Nullable<double> cena { get; set; }
        public Nullable<double> wartoscdosp { get; set; }
        public Nullable<byte> magazyn { get; set; }
        public Nullable<double> iloscpz { get; set; }
        public Nullable<double> stan { get; set; }
        public Nullable<double> wartoscst { get; set; }
        public string zapas { get; set; }
        public Nullable<System.DateTime> utowrzono { get; set; }
        public Nullable<System.DateTime> modyfikowano { get; set; }
    }
}
