//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LINIE_MASZYNY
    {
        public int id { get; set; }
        public int id_lini { get; set; }
        public int id_maszyny { get; set; }
    
        public virtual PROD_LINIE PROD_LINIE { get; set; }
        public virtual PROD_MASZYNY PROD_MASZYNY { get; set; }
    }
}
