//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODPARAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODPARAM()
        {
            this.PRODPARAM_WART = new HashSet<PRODPARAM_WART>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public string nazwa_grupy { get; set; }
        public byte czy_wart_licz { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> id_grupy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODPARAM_WART> PRODPARAM_WART { get; set; }
    }
}
