//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MGPW
    {
        public int id { get; set; }
        public int id_prodmz { get; set; }
        public int id_prodmgdw { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<int> lp { get; set; }
    
        public virtual PROD_MGDW PROD_MGDW { get; set; }
        public virtual PROD_MZ PROD_MZ { get; set; }
    }
}
