//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_PARAM_WART
    {
        public int id { get; set; }
        public int id_prod { get; set; }
        public int id_param { get; set; }
        public string wart { get; set; }
        public Nullable<int> lp { get; set; }
        public Nullable<int> id_prod_maszyny_pw { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD_MASZYNY_PARAM PROD_MASZYNY_PARAM { get; set; }
        public virtual PROD_MASZYNY_PW PROD_MASZYNY_PW { get; set; }
    }
}
