//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_MZ()
        {
            this.PROD_HMDW = new HashSet<PROD_HMDW>();
            this.PROD_MGDW = new HashSet<PROD_MGDW>();
            this.PROD_MGPW = new HashSet<PROD_MGPW>();
            this.PROD_PRODMGPW = new HashSet<PROD_PRODMGPW>();
            this.PROD_MZ_SPEC = new HashSet<PROD_MZ_SPEC>();
        }
    
        public int id { get; set; }
        public Nullable<int> idhm { get; set; }
        public int id_prodmg { get; set; }
        public Nullable<short> lp { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> idtw { get; set; }
        public string kod { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string opis { get; set; }
        public string opisdod { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<double> iloscrozliczona { get; set; }
        public string jm { get; set; }
        public Nullable<double> cena { get; set; }
        public Nullable<double> wartNetto { get; set; }
        public Nullable<int> idpozkoryg { get; set; }
        public Nullable<short> magazyn { get; set; }
        public Nullable<double> iloscjedn { get; set; }
        public Nullable<double> wartTowaru { get; set; }
        public Nullable<double> iloscwp { get; set; }
        public Nullable<int> idhandl { get; set; }
        public Nullable<double> iloscdorozl { get; set; }
        public Nullable<double> przychod { get; set; }
        public Nullable<double> rozchod { get; set; }
        public Nullable<int> id_partii { get; set; }
        public string nr_partii { get; set; }
        public Nullable<double> waga_brutto { get; set; }
        public Nullable<double> waga_tara { get; set; }
        public Nullable<double> waga_netto { get; set; }
        public string typ_produktu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_HMDW> PROD_HMDW { get; set; }
        public virtual PROD_MG PROD_MG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MGDW> PROD_MGDW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MGPW> PROD_MGPW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_PRODMGPW> PROD_PRODMGPW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MZ_SPEC> PROD_MZ_SPEC { get; set; }
    }
}
