//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LINIE_PW
    {
        public int id { get; set; }
        public int id_prod { get; set; }
        public int id_lini { get; set; }
        public int lp { get; set; }
        public string nazwa { get; set; }
        public string nazwa_procesu { get; set; }
        public string czas_pracy { get; set; }
        public Nullable<double> cena { get; set; }
        public Nullable<double> wartosc { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD_LINIE PROD_LINIE { get; set; }
    }
}
