//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_ZL
    {
        public int id { get; set; }
        public int id_maszyna_gl { get; set; }
        public int id_maszyna_dl { get; set; }
        public byte czy_monit_razem { get; set; }
    
        public virtual PROD_MASZYNY PROD_MASZYNY { get; set; }
        public virtual PROD_MASZYNY PROD_MASZYNY1 { get; set; }
    }
}
