//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_PRODMGPW
    {
        public int id { get; set; }
        public int id_proddp { get; set; }
        public Nullable<int> id_proddpmonit { get; set; }
        public double ilosc { get; set; }
        public Nullable<int> id_prodmgdw { get; set; }
        public Nullable<int> id_dkprodmg { get; set; }
        public Nullable<byte> status_rw { get; set; }
        public Nullable<byte> status_pw { get; set; }
    
        public virtual PROD_MGDW PROD_MGDW { get; set; }
        public virtual PROD_MZ PROD_MZ { get; set; }
        public virtual PRODDP PRODDP { get; set; }
        public virtual PRODDP_MONIT PRODDP_MONIT { get; set; }
    }
}
