//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_KOSZTY
    {
        public int id { get; set; }
        public int id_prod_maszyny_pw { get; set; }
        public int id_prod_maszyny_monit { get; set; }
        public string czas_pracy { get; set; }
        public Nullable<double> ilosc_kg { get; set; }
        public Nullable<double> cena_kg { get; set; }
        public Nullable<double> cena_czas { get; set; }
        public Nullable<double> wartosc_kg { get; set; }
        public Nullable<double> wartosc_czas { get; set; }
        public Nullable<byte> czy_wyliczono { get; set; }
    
        public virtual PROD_MASZYNY_MONIT PROD_MASZYNY_MONIT { get; set; }
        public virtual PROD_MASZYNY_PW PROD_MASZYNY_PW { get; set; }
    }
}
