//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LINIE_PARAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_LINIE_PARAM()
        {
            this.PROD_LINIE_PARAM_WART = new HashSet<PROD_LINIE_PARAM_WART>();
        }
    
        public int id { get; set; }
        public int id_lini { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public byte aktywny { get; set; }
    
        public virtual PROD_LINIE PROD_LINIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_PARAM_WART> PROD_LINIE_PARAM_WART { get; set; }
    }
}
