//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LINIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_LINIE()
        {
            this.PROD_LINIE_MASZYNY = new HashSet<PROD_LINIE_MASZYNY>();
            this.PROD_LINIE_PARAM = new HashSet<PROD_LINIE_PARAM>();
            this.PROD_LINIE_PW = new HashSet<PROD_LINIE_PW>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string nazwa_procesu { get; set; }
        public string kod_firmy { get; set; }
        public Nullable<double> cena { get; set; }
        public string jm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_MASZYNY> PROD_LINIE_MASZYNY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_PARAM> PROD_LINIE_PARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_LINIE_PW> PROD_LINIE_PW { get; set; }
    }
}
