//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LINIE_PARAM_WART
    {
        public int id { get; set; }
        public int id_prod { get; set; }
        public int id_param { get; set; }
        public string wart { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD_LINIE_PARAM PROD_LINIE_PARAM { get; set; }
    }
}
