//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_MASZYNY_PW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_MASZYNY_PW()
        {
            this.PROD_MASZYNY_KOSZTY = new HashSet<PROD_MASZYNY_KOSZTY>();
            this.PROD_MASZYNY_MONIT = new HashSet<PROD_MASZYNY_MONIT>();
            this.PROD_MASZYNY_PARAM_WART = new HashSet<PROD_MASZYNY_PARAM_WART>();
        }
    
        public int id { get; set; }
        public int id_prod { get; set; }
        public int id_prod_linie { get; set; }
        public int id_maszyny { get; set; }
        public string nazwa_maszyny { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD_MASZYNY PROD_MASZYNY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_KOSZTY> PROD_MASZYNY_KOSZTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_MONIT> PROD_MASZYNY_MONIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_MASZYNY_PARAM_WART> PROD_MASZYNY_PARAM_WART { get; set; }
    }
}
