//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_ZL
    {
        public int id { get; set; }
        public int id1 { get; set; }
        public int id2 { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string osoba { get; set; }
    
        public virtual PROD PROD { get; set; }
        public virtual PROD PROD1 { get; set; }
    }
}
