//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUROWCE
    {
        public long id { get; set; }
        public Nullable<int> id_surowca { get; set; }
        public Nullable<int> tw { get; set; }
        public Nullable<long> khid { get; set; }
        public string khnazwa { get; set; }
        public string khkod { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khkodpocz { get; set; }
        public string khnip { get; set; }
        public string khkraj { get; set; }
        public string numer_tel { get; set; }
        public Nullable<double> ilosc_surowca { get; set; }
        public string nazwa_surowca { get; set; }
        public Nullable<long> id_tw { get; set; }
        public string kod_tw { get; set; }
        public string pestycydy { get; set; }
        public Nullable<System.DateTime> pestycydy_data { get; set; }
        public string uwagi { get; set; }
        public string osoba { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> modyfikacja { get; set; }
        public string modyfikowal { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> realizacja { get; set; }
        public Nullable<double> realizacja_ilosc { get; set; }
        public Nullable<System.DateTime> data_realizacji { get; set; }
        public string rok_plantacji { get; set; }
        public Nullable<byte> pokos { get; set; }
        public string nr_partii { get; set; }
        public Nullable<System.DateTime> zbor_data { get; set; }
        public Nullable<double> pa_ilosc { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual SUROWCE_TW SUROWCE_TW { get; set; }
        public virtual TW TW1 { get; set; }
    }
}
