//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TW()
        {
            this.MG_STANY = new HashSet<MG_STANY>();
            this.MG_WG_POZYCJE = new HashSet<MG_WG_POZYCJE>();
            this.PARTIE = new HashSet<PARTIE>();
            this.PARTIE_2 = new HashSet<PARTIE_2>();
            this.PARTIE_ATESTY = new HashSet<PARTIE_ATESTY>();
            this.SUROWCE = new HashSet<SUROWCE>();
        }
    
        public int id { get; set; }
        public string osoba { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string kodpaskowy { get; set; }
        public Nullable<byte> vatsid { get; set; }
        public string jm { get; set; }
        public byte typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_STANY> MG_STANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_WG_POZYCJE> MG_WG_POZYCJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE> PARTIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_2> PARTIE_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIE_ATESTY> PARTIE_ATESTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUROWCE> SUROWCE { get; set; }
    }
}
