//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZYTKOWNICY_UPRAWNIENIA
    {
        public long id { get; set; }
        public int id_uzytkownika { get; set; }
        public string uprawnienia { get; set; }
    
        public virtual UZYTKOWNICY UZYTKOWNICY { get; set; }
    }
}
