//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZYTKOWNICY_LOG
    {
        public long id { get; set; }
        public string uzytkownik { get; set; }
        public System.DateTime data { get; set; }
        public string godz { get; set; }
        public string opis { get; set; }
        public string id_sesji { get; set; }
        public string sys_ip { get; set; }
        public string sys_host { get; set; }
        public string sys_uzytkownik { get; set; }
    }
}
