//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WZ_SPECYFIKACJE_TOWARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WZ_SPECYFIKACJE_TOWARY()
        {
            this.WZ_SPECYFIKACJE_OPAKOWANIA = new HashSet<WZ_SPECYFIKACJE_OPAKOWANIA>();
        }
    
        public int id { get; set; }
        public Nullable<byte> lp { get; set; }
        public int id_wzspec { get; set; }
        public int idtw { get; set; }
        public string kodtw { get; set; }
        public string nazwatw { get; set; }
        public string nazwatw2 { get; set; }
        public string nr_partii { get; set; }
        public string po { get; set; }
        public string kontrakt { get; set; }
        public string pos { get; set; }
        public string vendor { get; set; }
        public string mat { get; set; }
        public string zew_nrpartii { get; set; }
        public Nullable<System.DateTime> data_1 { get; set; }
        public Nullable<System.DateTime> data_2 { get; set; }
        public Nullable<System.DateTime> data_3 { get; set; }
        public Nullable<double> wbrutto { get; set; }
        public Nullable<double> wnetto { get; set; }
    
        public virtual WZ_SPECYFIKACJE WZ_SPECYFIKACJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WZ_SPECYFIKACJE_OPAKOWANIA> WZ_SPECYFIKACJE_OPAKOWANIA { get; set; }
    }
}
