//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WZ_SPECYFIKACJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WZ_SPECYFIKACJE()
        {
            this.WZ_SPECYFIKACJE_TOWARY = new HashSet<WZ_SPECYFIKACJE_TOWARY>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_dk { get; set; }
        public string kod_dk { get; set; }
        public string osoba { get; set; }
        public string kod { get; set; }
        public string seria { get; set; }
        public Nullable<int> serianr { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> datasp { get; set; }
        public string opis { get; set; }
        public Nullable<int> khid { get; set; }
        public string khkod { get; set; }
        public string khnazwa { get; set; }
        public string khadres { get; set; }
        public string khdom { get; set; }
        public string khlokal { get; set; }
        public string khmiasto { get; set; }
        public string khnip { get; set; }
        public string khkraj { get; set; }
        public Nullable<int> odid { get; set; }
        public string odkod { get; set; }
        public string odnazwa { get; set; }
        public string odadres { get; set; }
        public string oddom { get; set; }
        public string odlokal { get; set; }
        public string odmiasto { get; set; }
        public string odkodpocz { get; set; }
        public string odkraj { get; set; }
        public string odnip { get; set; }
        public Nullable<System.DateTime> aktualizacja { get; set; }
        public string jm { get; set; }
        public Nullable<float> wnetto { get; set; }
        public Nullable<float> wbrutto { get; set; }
        public string khkodpocz { get; set; }
        public string kod_firmy { get; set; }
        public string samochod { get; set; }
        public string warunki_dostawy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WZ_SPECYFIKACJE_TOWARY> WZ_SPECYFIKACJE_TOWARY { get; set; }
    }
}
