//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HERBS_PRODUKCJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WZ_SPECYFIKACJE_OPAKOWANIA
    {
        public int id { get; set; }
        public byte lp { get; set; }
        public Nullable<int> id_specwz { get; set; }
        public int id_wztow { get; set; }
        public string kodtw { get; set; }
        public Nullable<int> idtw { get; set; }
        public Nullable<double> ilosc { get; set; }
        public Nullable<double> ilewopakowaniu { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string godzina { get; set; }
        public Nullable<int> id_opakowania { get; set; }
        public string opakowanie_nazwa { get; set; }
        public Nullable<double> ilosc_opakowania { get; set; }
        public Nullable<double> waga_opakowania { get; set; }
        public string oznaczenie { get; set; }
        public Nullable<System.DateTime> termin_przydatnosci { get; set; }
        public string uwagi { get; set; }
    
        public virtual OPAKOWANIA_RODZAJE OPAKOWANIA_RODZAJE { get; set; }
        public virtual WZ_SPECYFIKACJE_TOWARY WZ_SPECYFIKACJE_TOWARY { get; set; }
    }
}
